import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Topbar, Profile, FavIcon, Content } from '../components'
import { getHomePosts } from '../services'
import { Post } from '../types'

export const getStaticProps: GetStaticProps = async () => {
  const posts = (await getHomePosts()) || []
  return {
    props: { posts },
  }
}

const Home: NextPage<{ posts: Post[] }> = (props) => {
  return (
    <div>
      <Head>
        <title>Yousef Omar</title>
        <meta name='description' content='Generated by create next app' />
        <FavIcon />
      </Head>
      <header className='profile container'>
        <Topbar />
        <Profile />
      </header>
      <Content posts={props.posts} />
      <footer className='footer container'>
        <span className='footer__copy'>
          &#169; Yousef Omar. All rigths reserved
        </span>
      </footer>
    </div>
  )
}
export default Home
